// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace practice.Models;

public partial class MumbaiIndiansContext : DbContext
{
    public MumbaiIndiansContext()
    {
    }

    public MumbaiIndiansContext(DbContextOptions<MumbaiIndiansContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TeamPlayer> TeamPlayers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=PANKAJ\\SQLEXPRESS;Initial Catalog=MumbaiIndians;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TeamPlayer>(entity =>
        {
            entity.HasKey(e => e.PlayerNo).HasName("PK__TeamPlay__4A4E6B7BEBB68E6B");

            entity.ToTable("TeamPlayer");

            entity.Property(e => e.PlayerName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}