// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace practice.Models;

public partial class TeamPlayer
{
    public int PlayerNo { get; set; }

    public string PlayerName { get; set; }

    public int? JesrsyNo { get; set; }
}